# Generated by Django 6.0.4 on 2026-04-09 12:46

import django.db.models.deletion
import partial_date.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "citation_key",
                    models.CharField(
                        db_index=True,
                        help_text="CSL JSON: citation-key (or id fallback). Unique per import batch.",
                        max_length=255,
                        verbose_name="citation key",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("article-journal", "Journal Article"),
                            ("article-magazine", "Magazine Article"),
                            ("article-newspaper", "Newspaper Article"),
                            ("bill", "Bill"),
                            ("book", "Book"),
                            ("broadcast", "Broadcast"),
                            ("chapter", "Chapter"),
                            ("classic", "Classic"),
                            ("collection", "Collection"),
                            ("dataset", "Dataset"),
                            ("document", "Document"),
                            ("entry", "Entry"),
                            ("entry-dictionary", "Dictionary Entry"),
                            ("entry-encyclopedia", "Encyclopedia Entry"),
                            ("event", "Event"),
                            ("figure", "Figure"),
                            ("graphic", "Graphic"),
                            ("hearing", "Hearing"),
                            ("interview", "Interview"),
                            ("legal_case", "Legal Case"),
                            ("legislation", "Legislation"),
                            ("manuscript", "Manuscript"),
                            ("map", "Map"),
                            ("motion_picture", "Motion Picture"),
                            ("musical_score", "Musical Score"),
                            ("pamphlet", "Pamphlet"),
                            ("paper-conference", "Conference Paper"),
                            ("patent", "Patent"),
                            ("performance", "Performance"),
                            ("periodical", "Periodical"),
                            ("personal_communication", "Personal Communication"),
                            ("post", "Post"),
                            ("post-weblog", "Blog Post"),
                            ("regulation", "Regulation"),
                            ("report", "Report"),
                            ("review", "Review"),
                            ("review-book", "Book Review"),
                            ("software", "Software"),
                            ("song", "Song"),
                            ("speech", "Speech"),
                            ("standard", "Standard"),
                            ("thesis", "Thesis"),
                            ("treaty", "Treaty"),
                            ("webpage", "Webpage"),
                        ],
                        db_index=True,
                        help_text="CSL JSON: type",
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_index=True, help_text="CSL JSON: title", max_length=1000, verbose_name="title"
                    ),
                ),
                (
                    "title_short",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: title-short (also imports deprecated shortTitle)",
                        max_length=500,
                        verbose_name="short title",
                    ),
                ),
                (
                    "original_title",
                    models.CharField(
                        blank=True, help_text="CSL JSON: original-title", max_length=500, verbose_name="original title"
                    ),
                ),
                (
                    "container_title",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="CSL JSON: container-title",
                        max_length=500,
                        verbose_name="container title",
                    ),
                ),
                (
                    "container_title_short",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: container-title-short",
                        max_length=255,
                        verbose_name="container title short",
                    ),
                ),
                (
                    "collection_title",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: collection-title",
                        max_length=500,
                        verbose_name="collection title",
                    ),
                ),
                (
                    "volume_title",
                    models.CharField(
                        blank=True, help_text="CSL JSON: volume-title", max_length=500, verbose_name="volume title"
                    ),
                ),
                (
                    "volume_title_short",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: volume-title-short",
                        max_length=255,
                        verbose_name="volume title short",
                    ),
                ),
                (
                    "part_title",
                    models.CharField(
                        blank=True, help_text="CSL JSON: part-title", max_length=500, verbose_name="part title"
                    ),
                ),
                (
                    "reviewed_title",
                    models.CharField(
                        blank=True, help_text="CSL JSON: reviewed-title", max_length=500, verbose_name="reviewed title"
                    ),
                ),
                (
                    "reviewed_genre",
                    models.CharField(
                        blank=True, help_text="CSL JSON: reviewed-genre", max_length=100, verbose_name="reviewed genre"
                    ),
                ),
                ("abstract", models.TextField(blank=True, help_text="CSL JSON: abstract", verbose_name="abstract")),
                ("note", models.TextField(blank=True, help_text="CSL JSON: note", verbose_name="note")),
                ("annote", models.TextField(blank=True, help_text="CSL JSON: annote", verbose_name="annotation")),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="CSL JSON: publisher",
                        max_length=255,
                        verbose_name="publisher",
                    ),
                ),
                (
                    "publisher_place",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: publisher-place",
                        max_length=255,
                        verbose_name="publisher place",
                    ),
                ),
                (
                    "original_publisher",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: original-publisher",
                        max_length=255,
                        verbose_name="original publisher",
                    ),
                ),
                (
                    "original_publisher_place",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: original-publisher-place",
                        max_length=255,
                        verbose_name="original publisher place",
                    ),
                ),
                (
                    "event_title",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: event-title (also imports deprecated event)",
                        max_length=500,
                        verbose_name="event title",
                    ),
                ),
                (
                    "event_place",
                    models.CharField(
                        blank=True, help_text="CSL JSON: event-place", max_length=255, verbose_name="event place"
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: volume (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="volume",
                    ),
                ),
                (
                    "issue",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: issue (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="issue",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        blank=True, help_text="CSL JSON: page (e.g. '171-175')", max_length=100, verbose_name="page"
                    ),
                ),
                (
                    "page_first",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: page-first (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="page first",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, help_text="CSL JSON: number", max_length=50, verbose_name="number"),
                ),
                (
                    "number_of_pages",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: number-of-pages (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="number of pages",
                    ),
                ),
                (
                    "number_of_volumes",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: number-of-volumes (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="number of volumes",
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: edition (string-or-number, e.g. '2nd', 3)",
                        max_length=50,
                        verbose_name="edition",
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, help_text="CSL JSON: version", max_length=50, verbose_name="version"),
                ),
                (
                    "chapter_number",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: chapter-number (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="chapter number",
                    ),
                ),
                (
                    "collection_number",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: collection-number (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="collection number",
                    ),
                ),
                (
                    "section",
                    models.CharField(blank=True, help_text="CSL JSON: section", max_length=100, verbose_name="section"),
                ),
                (
                    "part",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: part (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="part",
                    ),
                ),
                (
                    "supplement",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: supplement (string-or-number stored as string)",
                        max_length=100,
                        verbose_name="supplement",
                    ),
                ),
                (
                    "printing",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: printing (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="printing",
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, help_text="CSL JSON: status", max_length=50, verbose_name="status"),
                ),
                (
                    "medium",
                    models.CharField(blank=True, help_text="CSL JSON: medium", max_length=100, verbose_name="medium"),
                ),
                (
                    "genre",
                    models.CharField(blank=True, help_text="CSL JSON: genre", max_length=100, verbose_name="genre"),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: language (BCP 47 tag, e.g. 'en')",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "archive",
                    models.CharField(blank=True, help_text="CSL JSON: archive", max_length=255, verbose_name="archive"),
                ),
                (
                    "archive_collection",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: archive_collection (note: underscored in CSL JSON)",
                        max_length=255,
                        verbose_name="archive collection",
                    ),
                ),
                (
                    "archive_location",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: archive_location (note: underscored in CSL JSON)",
                        max_length=255,
                        verbose_name="archive location",
                    ),
                ),
                (
                    "archive_place",
                    models.CharField(
                        blank=True, help_text="CSL JSON: archive-place", max_length=255, verbose_name="archive place"
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True, help_text="CSL JSON: authority", max_length=255, verbose_name="authority"
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        blank=True, help_text="CSL JSON: jurisdiction", max_length=255, verbose_name="jurisdiction"
                    ),
                ),
                (
                    "call_number",
                    models.CharField(
                        blank=True, help_text="CSL JSON: call-number", max_length=100, verbose_name="call number"
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, help_text="CSL JSON: dimensions", max_length=100, verbose_name="dimensions"
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True, help_text="CSL JSON: division", max_length=100, verbose_name="division"
                    ),
                ),
                (
                    "scale",
                    models.CharField(blank=True, help_text="CSL JSON: scale", max_length=50, verbose_name="scale"),
                ),
                (
                    "source",
                    models.CharField(blank=True, help_text="CSL JSON: source", max_length=255, verbose_name="source"),
                ),
                (
                    "references",
                    models.TextField(blank=True, help_text="CSL JSON: references", verbose_name="references"),
                ),
                (
                    "journal_abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: journalAbbreviation (camelCase in CSL JSON)",
                        max_length=100,
                        verbose_name="journal abbreviation",
                    ),
                ),
                (
                    "citation_label",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: citation-label (processor-generated; stored for round-trip)",
                        max_length=100,
                        verbose_name="citation label",
                    ),
                ),
                (
                    "citation_number",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: citation-number (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="citation number",
                    ),
                ),
                (
                    "first_reference_note_number",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: first-reference-note-number (string-or-number stored as string)",
                        max_length=50,
                        verbose_name="first reference note number",
                    ),
                ),
                (
                    "locator",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: locator (string-or-number stored as string)",
                        max_length=100,
                        verbose_name="locator",
                    ),
                ),
                (
                    "year_suffix",
                    models.CharField(
                        blank=True, help_text="CSL JSON: year-suffix", max_length=10, verbose_name="year suffix"
                    ),
                ),
                (
                    "keyword",
                    models.TextField(
                        blank=True,
                        help_text="CSL JSON: keyword (single comma-separated string)",
                        verbose_name="keyword",
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        blank=True,
                        help_text="CSL JSON: categories (string array)",
                        null=True,
                        verbose_name="categories",
                    ),
                ),
                (
                    "custom",
                    models.JSONField(
                        blank=True,
                        help_text="CSL JSON: custom (arbitrary key-value pairs)",
                        null=True,
                        verbose_name="custom",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Name",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "family",
                    models.CharField(
                        blank=True, help_text="CSL JSON: family", max_length=255, verbose_name="family name"
                    ),
                ),
                (
                    "given",
                    models.CharField(
                        blank=True, help_text="CSL JSON: given", max_length=255, verbose_name="given name"
                    ),
                ),
                (
                    "dropping_particle",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: dropping-particle (e.g. 'von', 'van')",
                        max_length=50,
                        verbose_name="dropping particle",
                    ),
                ),
                (
                    "non_dropping_particle",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: non-dropping-particle (e.g. 'van der', 'de')",
                        max_length=50,
                        verbose_name="non-dropping particle",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: suffix (e.g. 'Jr.', 'III')",
                        max_length=50,
                        verbose_name="suffix",
                    ),
                ),
                (
                    "literal",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: literal (institutional names or unparsed strings)",
                        max_length=500,
                        verbose_name="literal",
                    ),
                ),
                (
                    "comma_suffix",
                    models.BooleanField(default=False, help_text="CSL JSON: comma-suffix", verbose_name="comma suffix"),
                ),
                (
                    "static_ordering",
                    models.BooleanField(
                        default=False,
                        help_text="CSL JSON: static-ordering (e.g. for East Asian names)",
                        verbose_name="static ordering",
                    ),
                ),
                (
                    "parse_names",
                    models.BooleanField(
                        default=False,
                        help_text="CSL JSON: parse-names (signal to CSL processor)",
                        verbose_name="parse names",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
            ],
            options={
                "verbose_name": "name",
                "verbose_name_plural": "names",
                "indexes": [models.Index(fields=["family", "given"], name="name_family_given_idx")],
            },
        ),
        migrations.CreateModel(
            name="ItemDate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "date_type",
                    models.CharField(
                        choices=[
                            ("accessed", "Accessed"),
                            ("available-date", "Available Date"),
                            ("event-date", "Event Date"),
                            ("issued", "Issued"),
                            ("original-date", "Original Date"),
                            ("submitted", "Submitted"),
                        ],
                        help_text="CSL JSON date-variable slot (e.g. issued, accessed, event-date).",
                        max_length=20,
                        verbose_name="date type",
                    ),
                ),
                (
                    "begin",
                    partial_date.fields.PartialDateField(
                        blank=True,
                        help_text="CSL JSON: date-parts[0] — start or single date with partial-date precision.",
                        null=True,
                        verbose_name="begin date",
                    ),
                ),
                (
                    "end",
                    partial_date.fields.PartialDateField(
                        blank=True,
                        help_text="CSL JSON: date-parts[1] — end date for ranges. Must not be set without begin.",
                        null=True,
                        verbose_name="end date",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: season ('1'=Spring, '2'=Summer, '3'=Autumn, '4'=Winter or custom)",
                        max_length=20,
                        verbose_name="season",
                    ),
                ),
                (
                    "circa",
                    models.BooleanField(
                        default=False, help_text="CSL JSON: circa — approximate date flag.", verbose_name="circa"
                    ),
                ),
                (
                    "literal",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: literal — free-text date when structured representation is impossible.",
                        max_length=255,
                        verbose_name="literal",
                    ),
                ),
                (
                    "raw",
                    models.CharField(
                        blank=True,
                        help_text="CSL JSON: raw — unparsed date string from source.",
                        max_length=255,
                        verbose_name="raw",
                    ),
                ),
                (
                    "raw_date_parts",
                    models.JSONField(
                        blank=True,
                        help_text="CSL JSON: date-parts — stores original array when normalization to PartialDate fails.",
                        null=True,
                        verbose_name="raw date parts",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The bibliographic item this date belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_dates",
                        to="literature.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "item date",
                "verbose_name_plural": "item dates",
                "indexes": [
                    models.Index(fields=["item", "date_type"], name="itemdate_item_date_type_idx"),
                    models.Index(fields=["begin"], name="itemdate_begin_idx"),
                    models.Index(fields=["end"], name="itemdate_end_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("item", "date_type"), name="unique_date_type_per_item")
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemIdentifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        help_text="Identifier type string (e.g. DOI, ISBN, ISSN, PMID, PMCID, URL, arXiv).",
                        max_length=50,
                        verbose_name="identifier type",
                    ),
                ),
                (
                    "value",
                    models.CharField(help_text="The identifier value string.", max_length=500, verbose_name="value"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The bibliographic item this identifier belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_identifiers",
                        to="literature.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "item identifier",
                "verbose_name_plural": "item identifiers",
                "indexes": [
                    models.Index(fields=["item", "type"], name="itemidentifier_item_type_idx"),
                    models.Index(fields=["type", "value"], name="itemidentifier_type_value_idx"),
                    models.Index(fields=["value"], name="itemidentifier_value_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("item", "type"), name="unique_identifier_type_per_item")
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("chair", "Chair"),
                            ("collection-editor", "Collection Editor"),
                            ("compiler", "Compiler"),
                            ("composer", "Composer"),
                            ("container-author", "Container Author"),
                            ("contributor", "Contributor"),
                            ("curator", "Curator"),
                            ("director", "Director"),
                            ("editor", "Editor"),
                            ("editorial-director", "Editorial Director"),
                            ("executive-producer", "Executive Producer"),
                            ("guest", "Guest"),
                            ("host", "Host"),
                            ("illustrator", "Illustrator"),
                            ("interviewer", "Interviewer"),
                            ("narrator", "Narrator"),
                            ("organizer", "Organizer"),
                            ("original-author", "Original Author"),
                            ("performer", "Performer"),
                            ("producer", "Producer"),
                            ("recipient", "Recipient"),
                            ("reviewed-author", "Reviewed Author"),
                            ("script-writer", "Script Writer"),
                            ("series-creator", "Series Creator"),
                            ("translator", "Translator"),
                        ],
                        help_text="CSL JSON name-variable field (e.g. author, editor, translator).",
                        max_length=30,
                        verbose_name="role",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Position of this contributor within the (item, role) group.",
                        verbose_name="order",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The bibliographic item this name is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_names",
                        to="literature.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        help_text="The name record for this contributor.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_names",
                        to="literature.name",
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "item name",
                "verbose_name_plural": "item names",
                "ordering": ["item", "role", "order"],
                "indexes": [
                    models.Index(fields=["item", "role", "order"], name="itemname_item_role_order_idx"),
                    models.Index(fields=["name", "role"], name="itemname_name_role_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("item", "role", "name"), name="unique_name_per_role_per_item")
                ],
            },
        ),
    ]
