# Generated by Django 5.2.13 on 2026-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemname',
            name='order',
            field=models.PositiveIntegerField(editable=False, help_text='Position of this contributor within the (item, role) group.', verbose_name='order'),
        ),
    ]
