# Generated by Django 5.2.13 on 2026-08-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0002_alter_itemname_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='citation_key',
            field=models.CharField(db_index=True, help_text='CSL JSON: citation-key (or id fallback). Need not be unique.', max_length=255, verbose_name='citation key'),
        ),
    ]
